### ISSUE TITLE
First `dt` is negative

### ISSUE THREAD

**Issue by xarvh** [xarvh/elm-gamepad#2]
It looks like `performance.now()` returns a timestamp that's a few milliseconds *ahead* of the first `timestamp` giveno to `window.requestAnimationFrame`'s callback; the result is that the first `dt` passed to the subscription is *negative*, ie about -10ms instead than the usual +16ms.

**Comment by ianmackenzie** [comment]
Just hit this myself - my fix was to change `gamepadPort.js` to use

```js
var previousTimestamp = null;

raf();

function raf() {
  requestAnimationFrame(onAnimationFrame);
}

function onAnimationFrame(timestamp) {
  raf();

  var serialisedGamepads = [];
  var gamepads = getGamepads();
  for (var i = 0; i < gamepads.length; i++) {
    serialisedGamepads.push(copyGamepad(gamepads[i]));
  }

  var delta = previousTimestamp === null ? 0 : timestamp - previousTimestamp;

  elmApp.ports.gamepadEvents.send([delta, serialisedGamepads]);

  previousTimestamp = timestamp;
}
```

**Comment by xarvh** [comment]
Thanks! =D
I wonder if it makes sense to do this in JS at all.
Maybe the port should just return the absolute timestamp and let the Elm code deal with it, to keep JS to the absolute minimum.

Pros:
* Less JS, more Elm
* More suitable for larger projects
* More accurate timekeeping, since the continuous addition will cause time to drift.

Cons:
* More work to use the library in small projects

What do you think @ianmackenzie ?

**Comment by ianmackenzie** [comment]
I lean slightly towards relative...in addition to the extra bookkeeping required for small projects, it sounds like there's some cross-browser differences to what that 'absolute' value means (epoch time vs. time since page load - see https://developers.google.com/web/updates/2012/05/requestAnimationFrame-API-now-with-sub-millisecond-precision). And the extra JS is pretty simple. I don't have strong opinions here though!

It would be interesting to measure the error between accumulating diffs and the actual returned absolute time, over the course of (say) a few hours...if it's significant, then that's a pretty strong argument.

**Comment by xarvh** [comment]
Fixed by https://github.com/xarvh/elm-gamepad/pull/13
